version: '3.0'
services:
  vps-demo-api:
    hostname: nyc
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    network_mode: "host"
